// swiftlint:disable line_length
//
//  Constants.swift
//  victory
//
//  Created by Wuri Dita on 10/06/21.
//

import Foundation

class Constants {
    static let panduanLabs = [
        Panduanlab(langkah: ["Tujuan Lab 1: Menentukan pengaruh massa dalam gerak parabola. Langkah-langkahnya adalah sebagai berikut", "Pada Lab 1, variabel sudut lemparan (θ) sebesar 30° dan kecepatan awal (vo) sebesar 100 m/s bernilai konstan", "Pada bagian Variabel, atur massa proyektil sebesar 1 kg kemudian luncurkan proyektil tersebut", "Amati jarak tembaknya (Xmax), isi tabel lembar kerja", "Hitung ketinggian maksimum yang dapat dicapai proyektil (Ymax) dan waktu yang dibutuhkan untuk menempuh ketinggian maksimum (t(Ymax)), isi tabel lembar kerja", "Ulangi langkah 2,3,4 namun menggunakan proyektil dengan massa 10, 50, 100, dan 200 kg", "Jika jawaban pada tabel lembar kerja sudah tepat, maka isian akan berubah warna menjadi hijau"]),
        Panduanlab(langkah: ["Tujuan Lab 2: Menentukan pengaruh sudut lemparan dalam gerak parabola. Langkah-langkahnya adalah sebagai berikut", "Pada Lab 2, variabel kecepatan awal (vo) sebesar 100 m/s dan massa proyektil sebesar 50 kg bernilai konstan", "Pada bagian Variabel, atur sudut lemparan (θ) sebesar 0° kemudian luncurkan proyektil tersebut", "Amati jarak tembaknya (Xmax), isi tabel lembar kerja", "Hitung ketinggian maksimum yang dapat dicapai proyektil (Ymax) dan waktu yang dibutuhkan untuk menempuh ketinggian maksimum (t(Ymax)), isi tabel lembar kerja", "Ulangi langkah 2,3,4 namun menggunakan sudut lemparan 30°, 45°, 60°, dan 90°", "Jika jawaban pada tabel lembar kerja sudah tepat, maka isian akan berubah warna menjadi hijau"]),
        Panduanlab(langkah: ["Tujuan Lab 3: Menentukan pengaruh kecepatan awal dalam gerak parabola. Langkah-langkahnya adalah sebagai berikut", "Pada Lab 3, variabel variabel sudut lemparan (θ) sebesar 45° dan massa proyektil sebesar 50 kg bernilai konstan", "Pada bagian Variabel, atur kecepatan awal (vo) sebesar 10 m/s kemudian luncurkan proyektil tersebut", "Amati jarak tembaknya (Xmax), isi tabel lembar kerja", "Hitung ketinggian maksimum yang dapat dicapai proyektil (Ymax) dan waktu yang dibutuhkan untuk menempuh ketinggian maksimum (t(Ymax)), isi tabel lembar kerja", "Ulangi langkah 2,3,4 namun menggunakan kecepatan awal sebesar 20, 30, 40, dan 50 m/s", "Jika jawaban pada tabel lembar kerja sudah tepat, maka isian akan berubah warna menjadi hijau"])
    ]
    static let pertanyaanArray = [
        Quiz(questionNumber: "Nomor 1", question: "Dari praktikum yang kamu lakukan, apa pengaruh massa terhadap ketinggian proyektil?", answer: ["A. Semakin besar massa, maka tinggi maksimum proyektil juga akan semakin besar, dan sebaliknya", "B. Semakin besar massa, maka tinggi maksimum proyektil juga akan semakin kecil, dan sebaliknya", "C. Semakin kecil massa, maka tinggi maksimum proyektil juga akan semakin besar, dan sebaliknya", "D. Massa tidak berpengaruh pada ketinggian maksimum proyektil"], correctAnswer: "D. Massa tidak berpengaruh pada ketinggian maksimum proyektil", correctAnswerKey: .optionD, explaination: "Sesuai dengan persamaan: y = v0 sin Θ - 1/2gt^2 sehingga dapat disimpulkan bahwa massa tidak berpengaruh pada ketinggian proyektil."),
        Quiz(questionNumber: "Nomor 2", question: "Dari praktikum yang kamu lakukan, apa pengaruh massa terhadap jarak maksimum proyektil?", answer: ["A. Semakin besar massa, maka jarak maksimum yang ditempuh proyektil juga akan semakin jauh, dan sebaliknya", "B. Semakin besar massa, maka jarak maksimum yang ditempuh proyektil juga akan semakin dekat, dan sebaliknya", "C. Semakin kecil massa, maka jarak maksimum yang ditempuh proyektil juga akan semakin jauh dan sebaliknya", "D. Massa tidak berpengaruh pada jarak maksimum yang ditempuh proyektil"], correctAnswer: "D. Massa tidak berpengaruh pada jarak maksimum yang ditempuh proyektil", correctAnswerKey: .optionD, explaination: "Sesuai dengan persamaan: x = v0 cos Θ t sehingga dapat disimpulkan bahwa massa tidak berpengaruh pada jarak maksimum yang ditempuh proyektil."),
        Quiz(questionNumber: "Nomor 3", question: "Dari praktikum yang kamu lakukan, jika kecepatan awal benda makin besar maka tinggi maksimum yang ditempuh benda akan …", answer: ["A. semakin besar", "B. semakin kecil", "C. sama saja", "D. tidak dapat ditentukan"], correctAnswer: "A. semakin besar", correctAnswerKey: .optionA, explaination: "Sesuai dengan persamaan INI PERSAMAANNYA BELOM YA. Kecepatan awal berbanding lurus dengan tinggi maksimum benda, jika kecepatan awal makin besar, maka tinggi maksimum yang dicapai benda juga akan semakin besar, dan sebaliknya jika kecepatan awal semakin kecil, maka tinggi maksimum juga semakin kecil.Sehingga dapat disimpulkan bahwa semakin besar kecepatan awal benda maka tinggi maksimum yang dicapai juga akan semakin besar."),
        Quiz(questionNumber: "Nomor 4", question: "Dari praktikum yang kamu lakukan, sudut yang mempunyai jarak maksimum yang terjauh adalah…", answer: ["A. 30°", "B. 45°", "C. 60°", "D. 90°"], correctAnswer: "B. 45°", correctAnswerKey: .optionB, explaination: "Berdasarkan percobaan yang telah dilakukan, diketahui bahwa sudut dengan jarak maksimum adalah 45°. Dapat dibuktikan oleh persamaan: INI BELOM PERSAMAANNYA dimana nilai maksimum dari sin 2Θ  sebesar 1 dapat diperoleh dengan  sebesar  45°."),
        Quiz(questionNumber: "Nomor 5", question: "Dari praktikum yang kamu lakukan, sudut yang mempunyai tinggi maksimum tertinggi adalah…", answer: ["A. 30°", "B. 45°", "C. 60°", "D. 90°"], correctAnswer: "D. 90°", correctAnswerKey: .optionD, explaination: "Berdasarkan percobaan yang telah dilakukan, diketahui bahwa sudut dengan ketinggian maksimum adalah 90°. Dapat dibuktikan dengan persamaan: dimana nilai maksimum dari sin kuadrat Θ sebesar 1 dapat diperoleh dengan  sebesar 90°.")
        ]
}
